# Generated by Django 6.1 on 2026-08-22 14:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produto', models.CharField(max_length=120, verbose_name='Produto comprado')),
                ('nome_fornecedor', models.CharField(max_length=120, verbose_name='Nome do fornecedor')),
                ('preco_unidade', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço da unidade')),
                ('preco_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço total pago')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fornecedores', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('quantidade', models.PositiveIntegerField(default=0)),
                ('validade', models.DateField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['validade'],
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mesa', models.PositiveSmallIntegerField(choices=[(1, 'Mesa 1'), (2, 'Mesa 2'), (3, 'Mesa 3'), (4, 'Mesa 4'), (5, 'Mesa 5'), (6, 'Mesa 6'), (7, 'Mesa 7'), (8, 'Mesa 8'), (9, 'Mesa 9'), (10, 'Mesa 10'), (11, 'Mesa 11'), (12, 'Mesa 12'), (13, 'Mesa 13'), (14, 'Mesa 14'), (15, 'Mesa 15')])),
                ('cliente_nome', models.CharField(max_length=120)),
                ('cliente_telefone', models.CharField(blank=True, max_length=20)),
                ('data', models.DateField()),
                ('horario', models.TimeField(help_text='Horário de funcionamento: 18:00 até 01:00')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['data', 'horario', 'mesa'],
                'unique_together': {('mesa', 'data', 'horario')},
            },
        ),
    ]
