# Generated by Django 6.1 on 2026-08-22 14:51
# Reescrita para funcionar com dados já existentes (MySQL/PostgreSQL): em vez de
# trocar o CharField por uma ForeignKey direto, os nomes de produto antigos são
# ligados (ou criados) como Produto antes de a coluna virar obrigatória.

import datetime

import django.db.models.deletion
from django.db import migrations, models


def ligar_produtos(apps, schema_editor):
    Fornecedor = apps.get_model('restaurante_app', 'Fornecedor')
    Produto = apps.get_model('restaurante_app', 'Produto')
    for compra in Fornecedor.objects.all():
        nome = (compra.produto_texto or '').strip() or 'Produto sem nome'
        produto = Produto.objects.filter(usuario_id=compra.usuario_id, nome__iexact=nome).order_by('pk').first()
        if produto is None:
            produto = Produto.objects.create(
                usuario_id=compra.usuario_id, nome=nome, quantidade=0,
                validade=datetime.date.today(),
            )
        compra.produto_id = produto.pk
        compra.save(update_fields=['produto'])


class Migration(migrations.Migration):

    dependencies = [
        ('restaurante_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fornecedor',
            name='preco_total',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10, verbose_name='Preço total pago'),
        ),
        migrations.RenameField(
            model_name='fornecedor',
            old_name='produto',
            new_name='produto_texto',
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='produto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='compras', to='restaurante_app.produto', verbose_name='Produto comprado'),
        ),
        migrations.RunPython(ligar_produtos, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='fornecedor',
            name='produto_texto',
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compras', to='restaurante_app.produto', verbose_name='Produto comprado'),
        ),
    ]
