# Generated by Django 6.1 on 2026-08-22 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurante_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fornecedor',
            name='preco_total',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10, verbose_name='Preço total pago'),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compras', to='restaurante_app.produto', verbose_name='Produto comprado'),
        ),
    ]
