# Generated by Django 5.0.14 on 2026-08-23 23:08

import django.db.models.deletion
import secrets
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurante_app', '0002_alter_fornecedor_preco_total_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorESP32',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Ex: ESP32 - Câmara fria 1', max_length=50)),
                ('token', models.CharField(default=secrets.token_hex, editable=False, max_length=64, unique=True)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensores', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sensor ESP32',
                'verbose_name_plural': 'Sensores ESP32',
            },
        ),
        migrations.CreateModel(
            name='ZonaTemperatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zona', models.CharField(choices=[('A', 'Zona A'), ('B', 'Zona B'), ('C', 'Zona C'), ('D', 'Zona D')], max_length=1)),
                ('temp_minima', models.DecimalField(decimal_places=2, max_digits=5)),
                ('temp_maxima', models.DecimalField(decimal_places=2, max_digits=5)),
                ('temp_atual', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zonas_temperatura', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Zona de Temperatura',
                'verbose_name_plural': 'Zonas de Temperatura',
                'ordering': ['zona'],
                'unique_together': {('usuario', 'zona')},
            },
        ),
    ]
