# Generated by Django 5.0.14 on 2026-08-24 23:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurante_app', '0003_sensoresp32_zonatemperatura'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unidade', models.CharField(choices=[('kg', 'Quilograma (kg)'), ('l', 'Litro (L)'), ('un', 'Unidade')], default='un', max_length=2)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_estoque', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
