# Generated by Django 5.0.14 on 2026-08-25 00:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurante_app', '0004_itemestoque'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='unidade',
            field=models.CharField(choices=[('kg', 'Quilograma (kg)'), ('l', 'Litro (L)'), ('un', 'Unidade')], default='un', max_length=2, verbose_name='Unidade'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='pago',
            field=models.BooleanField(default=False, verbose_name='Pagamento confirmado'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='quantidade_pessoas',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Quantidade de pessoas'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='tipo_pagamento',
            field=models.CharField(choices=[('dinheiro', 'Dinheiro'), ('debito', 'Cartão de Débito'), ('credito', 'Cartão de Crédito'), ('pix', 'Pix')], default='dinheiro', max_length=10, verbose_name='Tipo de pagamento'),
        ),
        migrations.CreateModel(
            name='DespesaFixa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('aluguel', 'Aluguel'), ('agua', 'Água'), ('energia', 'Energia'), ('outros', 'Outros')], max_length=10, verbose_name='Tipo')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('mes', models.PositiveSmallIntegerField(choices=[(1, 'Janeiro'), (2, 'Fevereiro'), (3, 'Março'), (4, 'Abril'), (5, 'Maio'), (6, 'Junho'), (7, 'Julho'), (8, 'Agosto'), (9, 'Setembro'), (10, 'Outubro'), (11, 'Novembro'), (12, 'Dezembro')], verbose_name='Mês')),
                ('ano', models.PositiveSmallIntegerField(verbose_name='Ano')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='despesas_fixas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Despesa Fixa',
                'verbose_name_plural': 'Despesas Fixas',
                'ordering': ['-ano', '-mes', 'tipo'],
            },
        ),
    ]
