# Generated by Django 5.1.6 on 2026-08-28 20:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurante_app', '0005_produto_unidade_reserva_pago_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='quantidade_minima',
            field=models.PositiveIntegerField(default=5, help_text='Abaixo desse valor, um alerta de estoque baixo é disparado.', verbose_name='Quantidade mínima'),
        ),
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('temperatura', 'Temperatura'), ('validade', 'Produto vencendo'), ('estoque', 'Estoque baixo')], max_length=20)),
                ('mensagem', models.CharField(max_length=255)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('resolvida', models.BooleanField(default=False)),
                ('produto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to='restaurante_app.produto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to=settings.AUTH_USER_MODEL)),
                ('zona', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to='restaurante_app.zonatemperatura')),
            ],
            options={
                'verbose_name': 'Notificação',
                'verbose_name_plural': 'Notificações',
                'ordering': ['-criada_em'],
            },
        ),
    ]
