# Generated by Django 5.1.6 on 2026-08-30 11:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurante_app', '0006_produto_quantidade_minima_notificacao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='categoria',
            field=models.CharField(choices=[('bebidas', 'Bebidas'), ('carnes', 'Carnes e Peixes'), ('laticinios', 'Laticínios'), ('hortifruti', 'Hortifruti'), ('graos_massas', 'Grãos e Massas'), ('limpeza', 'Limpeza'), ('descartaveis', 'Descartáveis'), ('outros', 'Outros')], default='outros', max_length=20, verbose_name='Categoria'),
        ),
        migrations.CreateModel(
            name='MovimentacaoEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada (compra)'), ('saida', 'Saída (uso/consumo)'), ('perda', 'Perda/Descarte'), ('ajuste', 'Ajuste de contagem')], max_length=10)),
                ('quantidade', models.PositiveIntegerField(help_text='Quantidade movimentada (sempre um valor positivo).')),
                ('quantidade_resultante', models.PositiveIntegerField(editable=False, verbose_name='Quantidade em estoque após o movimento')),
                ('observacao', models.CharField(blank=True, max_length=200)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimentacoes', to='restaurante_app.produto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimentacoes_estoque', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Movimentação de Estoque',
                'verbose_name_plural': 'Movimentações de Estoque',
                'ordering': ['-criado_em'],
            },
        ),
    ]
