# Generated by Django 5.1.6 on 2026-09-01 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurante_app', '0007_produto_categoria_movimentacaoestoque'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='quantidade_maxima',
            field=models.PositiveIntegerField(blank=True, help_text='Acima desse valor, indica estoque excessivo (compra além do necessário). Opcional.', null=True, verbose_name='Quantidade máxima'),
        ),
    ]
