# Generated by Django 5.1.6 on 2026-09-01 18:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurante_app', '0008_produto_quantidade_maxima'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reserva',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='reserva',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notificacao',
            name='tipo',
            field=models.CharField(choices=[('temperatura', 'Temperatura'), ('validade', 'Produto vencendo'), ('estoque', 'Estoque baixo'), ('excesso', 'Estoque excedente')], max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='reserva',
            unique_together={('usuario', 'mesa', 'data', 'horario')},
        ),
        migrations.CreateModel(
            name='Prato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('preco_venda', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pratos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='ItemFichaTecnica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_usada', models.PositiveIntegerField(help_text='Quantidade deste produto consumida ao preparar 1 unidade do prato.')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usado_em_pratos', to='restaurante_app.produto')),
                ('prato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_ficha_tecnica', to='restaurante_app.prato')),
            ],
            options={
                'verbose_name': 'Item da Ficha Técnica',
                'verbose_name_plural': 'Itens da Ficha Técnica',
                'unique_together': {('prato', 'produto')},
            },
        ),
    ]
