# Generated by Django 5.1.15 on 2026-10-03 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurante_app', '0009_alter_reserva_unique_together_reserva_usuario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensoresp32',
            name='tipo_sensor',
            field=models.CharField(choices=[('DHT22', 'DHT22 (temperatura e umidade)'), ('DS18B20', 'DS18B20 (temperatura - freezer)')], default='DHT22', max_length=10),
        ),
        migrations.AddField(
            model_name='sensoresp32',
            name='zona',
            field=models.CharField(blank=True, choices=[('A', 'Zona A'), ('B', 'Zona B'), ('C', 'Zona C'), ('D', 'Zona D')], help_text='Trava este sensor a UMA zona específica (ex: Zona A pro DS18B20 do freezer). Se o token for usado pra enviar uma zona diferente desta, o envio é recusado. Deixe em branco se este token enviar mais de uma zona.', max_length=1, null=True),
        ),
    ]