# Generated by Django 5.1.15 on 2026-10-08 18:20


import django.core.validators
import django.db.models.deletion
import restaurante_app.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


def preencher_dados(apps, schema_editor):
    """Leva os dados antigos para o novo modelo (executa depois de todas as mudanças de estrutura)."""
    Fornecedor = apps.get_model('restaurante_app', 'Fornecedor')
    Movimentacao = apps.get_model('restaurante_app', 'MovimentacaoEstoque')
    Pedido = apps.get_model('restaurante_app', 'Pedido')
    Perfil = apps.get_model('restaurante_app', 'PerfilRestaurante')
    User = apps.get_model('auth', 'User')

    # Compras: a quantidade comprada passa a ser da própria compra. Como o total
    # antigo era (estoque da época × preço), quantidade = total ÷ preço mantém o
    # valor financeiro exatamente igual ao que já estava registrado.
    for compra in Fornecedor.objects.select_related('produto'):
        quantidade = Decimal('0')
        if compra.preco_unidade:
            quantidade = (compra.preco_total / compra.preco_unidade).quantize(Decimal('0.01'))
        Fornecedor.objects.filter(pk=compra.pk).update(
            quantidade=quantidade,
            nome_produto=compra.produto.nome if compra.produto_id else '',
        )

    for mov in Movimentacao.objects.select_related('produto'):
        if mov.produto_id:
            Movimentacao.objects.filter(pk=mov.pk).update(nome_produto=mov.produto.nome)

    # Pedidos antigos já tinham baixado o estoque na hora: viram "confirmado".
    # As saídas deles são ligadas ao pedido (pelo texto da observação) para que
    # um cancelamento futuro consiga devolver o estoque.
    for pedido in Pedido.objects.filter(status='recebido'):
        Movimentacao.objects.filter(
            usuario_id=pedido.usuario_id, tipo='saida', pedido__isnull=True,
            observacao__startswith=f'Pedido #{pedido.pk} (',
        ).update(pedido=pedido)
    Pedido.objects.filter(status='recebido').update(status='confirmado')

    for usuario in User.objects.all():
        Perfil.objects.get_or_create(usuario=usuario)


class Migration(migrations.Migration):

    dependencies = [
        ('restaurante_app', '0011_pedido_itempedido'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilRestaurante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug_publico', models.CharField(default=restaurante_app.models.gerar_slug_publico, editable=False, max_length=20, unique=True)),
                ('nome_exibicao', models.CharField(blank=True, help_text='Aparece no topo do cardápio do cliente. Deixe em branco para não mostrar nome.', max_length=80, verbose_name='Nome exibido ao cliente')),
            ],
            options={
                'verbose_name': 'Perfil do Restaurante',
                'verbose_name_plural': 'Perfis dos Restaurantes',
            },
        ),
        migrations.RemoveField(
            model_name='itemestoque',
            name='usuario',
        ),
        migrations.AlterUniqueTogether(
            name='reserva',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='nome_produto',
            field=models.CharField(blank=True, editable=False, max_length=120),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='quantidade',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Quantidade comprada'),
        ),
        migrations.AddField(
            model_name='movimentacaoestoque',
            name='nome_produto',
            field=models.CharField(blank=True, editable=False, max_length=120),
        ),
        migrations.AddField(
            model_name='movimentacaoestoque',
            name='pedido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentacoes', to='restaurante_app.pedido'),
        ),
        migrations.AlterField(
            model_name='despesafixa',
            name='ano',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2100)], verbose_name='Ano'),
        ),
        migrations.AlterField(
            model_name='despesafixa',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Valor'),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='preco_unidade',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Preço da unidade'),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='produto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compras', to='restaurante_app.produto', verbose_name='Produto comprado'),
        ),
        migrations.AlterField(
            model_name='itemfichatecnica',
            name='quantidade_usada',
            field=models.DecimalField(decimal_places=2, help_text='Quantidade deste produto consumida ao preparar 1 unidade do prato.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='movimentacaoestoque',
            name='produto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentacoes', to='restaurante_app.produto'),
        ),
        migrations.AlterField(
            model_name='movimentacaoestoque',
            name='quantidade',
            field=models.DecimalField(decimal_places=2, help_text='Quantidade movimentada (sempre um valor positivo).', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='movimentacaoestoque',
            name='quantidade_resultante',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10, verbose_name='Quantidade em estoque após o movimento'),
        ),
        migrations.AlterField(
            model_name='movimentacaoestoque',
            name='tipo',
            field=models.CharField(choices=[('entrada', 'Entrada (compra)'), ('saida', 'Saída (uso/consumo)'), ('perda', 'Perda/Descarte'), ('ajuste', 'Ajuste de contagem'), ('estorno', 'Estorno (pedido cancelado)')], max_length=10),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='mesa',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Mesa 1'), (2, 'Mesa 2'), (3, 'Mesa 3'), (4, 'Mesa 4'), (5, 'Mesa 5'), (6, 'Mesa 6'), (7, 'Mesa 7'), (8, 'Mesa 8'), (9, 'Mesa 9'), (10, 'Mesa 10'), (11, 'Mesa 11'), (12, 'Mesa 12'), (13, 'Mesa 13'), (14, 'Mesa 14'), (15, 'Mesa 15')], null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('recebido', 'Recebido'), ('confirmado', 'Confirmado'), ('entregue', 'Entregue'), ('cancelado', 'Cancelado')], default='recebido', max_length=10),
        ),
        migrations.AlterField(
            model_name='produto',
            name='quantidade',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='produto',
            name='quantidade_maxima',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Acima desse valor, indica estoque excessivo (compra além do necessário). Opcional.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Quantidade máxima'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='quantidade_minima',
            field=models.DecimalField(decimal_places=2, default=5, help_text='Quando o estoque chegar a esse valor (ou ficar abaixo dele), um alerta de estoque baixo é disparado.', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Quantidade mínima'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='quantidade_pessoas',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantidade de pessoas'),
        ),
        migrations.AddConstraint(
            model_name='produto',
            constraint=models.CheckConstraint(condition=models.Q(('quantidade__gte', 0)), name='produto_quantidade_nao_negativa'),
        ),
        migrations.AddConstraint(
            model_name='reserva',
            constraint=models.UniqueConstraint(fields=('usuario', 'mesa', 'data', 'horario'), name='reserva_unica_por_usuario'),
        ),
        migrations.AddConstraint(
            model_name='reserva',
            constraint=models.UniqueConstraint(condition=models.Q(('usuario__isnull', True)), fields=('mesa', 'data', 'horario'), name='reserva_unica_sem_usuario'),
        ),
        migrations.AddField(
            model_name='perfilrestaurante',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='ItemEstoque',
        ),
        migrations.RunPython(preencher_dados, migrations.RunPython.noop),
    ]
